apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: falco
  namespace: flux-system  
spec:
  chart:
    spec:
      chart: falcosecurity
      sourceRef:
        kind: HelmRepository
        name: falcosecurity
      version: '3.8.4'
  interval: 2m
  releaseName: falcosecurity
  targetNamespace: security
  values:
    driver:
      kind: ebpf
    tty: true
    falcosidekick:
      enabled: true
      config:
        customfields:
          user: "flux"