apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: flux-system  
spec:
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: kube-prometheus-stack
      version: '52.1.0'
  interval: 2m
  releaseName: monitoring
  targetNamespace: monitoring
  values:
    grafana:
      service:
        type: LoadBalancer
      ingress:
        enabled: false
