apiVersion: apps/v1
kind: Deployment
metadata:
  name: windows-webserver
  labels:
    app: windows-webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: windows-webserver
  template:
    metadata:
      labels:
        app: windows-webserver
    spec:
      containers:
      - name: iis-container
        image: mcr.microsoft.com/windows/servercore/iis:windowsservercore-ltsc2019
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "1Gi"
            cpu: "1"
          limits:
            memory: "2Gi"
            cpu: "2"
        securityContext:
          windowsOptions:
            runAsUserName: "ContainerUser"
          readOnlyRootFilesystem: true
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
      nodeSelector:
        "kubernetes.io/os": windows
      tolerations:
      - key: "os"
        operator: "Equal"
        value: "windows"
        effect: "NoSchedule"