apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  releaseName: ingress-nginx
  targetNamespace: ingress-nginx
  chart: ingress-nginx
  sourceRef:
    kind: HelmRepository
    name: ingress-nginx
  version: '4.8.3'
  
