apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: ingress-nginx
  namespace: ingress-nginx  # Replace with the desired namespace
spec:
  sourceRef:
    kind: GitRepository
    name: https://github.com/amestofortytwo/antonsen_test/
  path: applications
  prune: true
