apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: ingress-nginx
spec:
  releaseName: nginx-ingress
  chart:
    repository: https://kubernetes.github.io/ingress-nginx
    name: ingress-nginx
    version: 1.9.4
  values:
    controller:
      scope:
        enabled: true
    controllerService:
      type: LoadBalancer
    rbac:
      create: true
  targetNamespace: ingress-nginx

