apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: cert-manager
resources:
- cert-manager/namespace.yml
- cert-manager/repository.yml
- cert-manager/release.yml
