# Default deny for argocd namespace
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-argocd
  namespace: argocd
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress