apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

replacements:
  - source:
      kind: Service
      name: ingress-nginx-controller
      namespace: ingress-nginx
      fieldPath: status.loadBalancer.ingress[0].ip
    targets:
      - select:
          kind: Ingress
          name: argocd-server
          namespace: argocd
        fieldPaths:
          - spec.rules[0].host
