apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: argocd
spec:
  chart:
    spec:
      chart: argo-cd
      sourceRef:
        kind: HelmRepository
        name: argo
      version: '5.48.0'
  interval: 1h0s
  releaseName: argocd
