apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: argocd
  namespace: flux-system  
spec:
  chart:
    spec:
      chart: argo-cd
      sourceRef:
        kind: HelmRepository
        name: argo
      version: '5.48.0'
  interval: 1h0s
  releaseName: argocd
  targetNamespace: argocd
  values:
    networkPolicy:
      create: true
    server:
      service:
        type: ClusterIP
      ingress:
        enabled: true
        ingressClassName: "nginx"
        hosts:
          - "placeholder.com"
        paths:
          - /argocd